# Generated by Django 3.0.14 on 2023-02-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20230227_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='register_email',
            new_name='organizer_email',
        ),
    ]
